spring:
  datasource:
    #url: jdbc:mysql://db4free.net:3306/j9_quemirasbobo
    #username: quemirasbobosoft
    #password: quemirasbobo
    url: jdbc:mysql://localhost:3306/j9_quemirasbobo
    username: ironhacker
    password: 1r0nh4ck3r
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: "off"
  jpa:
    show-sql: false
    hibernate:
        ddl-auto: none
server:
  port: 8090
logging:
  level:
    root: off